CREATE TABLE [dbo].[User]
(
	[UserId] INT NOT NULL IDENTITY(1,1),
	[UserName] NVARCHAR(50) UNIQUE NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[ModifiedDate] DATETIME2 default(SYSUTCDATETIME()),
	CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED(USERID)
)
